Iter3: finalize project with withdraw handler and tests
Makovey/gophermart pull request #3
Opened 2024-12-22 10:11 UTC by Makovey

2025-01-09 17:38 UTC, bulbetski reviewed
досмотрю чуть позже

2025-01-09 17:38 UTC, bulbetski commented on internal/app/app.go
> +
Тут в двух местах в случае ошибки работа продолжается. Так и хотел?

2025-01-09 17:38 UTC, bulbetski commented on internal/app/app.go
> +	deps *deps
Вкусовщина. Много как-то точечек при вызове логгера может плоско сделаешь без структуры deps? При этом также оставишь методы с конфигом и логером

2025-01-09 17:38 UTC, bulbetski commented on internal/app/deps.go
> +}
Кароч это всё плоско добавляем в App. Все зависимости инициализируем в main. Все конструкторы структур должны возвращать ошибки (ну из тех, кто реально может), а не паниковать. Про паники забудь -- они рушат флоу приложения -- только обработка ошибок.

2025-01-09 17:38 UTC, bulbetski commented on internal/config/config.go
> +	}
Логика по выбору значения конфигурации дублируется в каждом методе. Это затрудняет добавление новых параметров конфигурации.

Логика определения значений конфигурации перемешана с конструкцией самого объекта конфигурации. Это нарушает принцип единственной ответственности (SRP

Сделай отдельно централизованный метод parseConfig, обработай там все энвы и флаги и на выходе получи конфиг.

2025-01-09 17:38 UTC, bulbetski commented on internal/db/migrations/20241130124046_new_gophermart_users_table.sql
> +    created_at TIMESTAMP DEFAULT (current_timestamp AT TIME ZONE 'Europe/Moscow')
можно NOT NULL добавить, полезная строчка. А вот time zone 50/50 конечно тема для бд. 
лучше просто сделать timestamp with timezone и потом просто селектить в нужной таймзоне, т.к. типа настройка базы или то, что ты вставляешь можешь отличаться от твоего дефолтного значения

2025-01-09 17:38 UTC, bulbetski commented on internal/repository/postgresql/balances_repository.go
> +}
1 раз напишу. Нет смысла пилить 3 н-ное количество репозиториев под разные нужды. Создай все свои репозиторные методы в рамках 1 репозитория и раздели просто файлами. В месте использования создашь интерфейсы: у order сервиса будет type OrderRepositoryInterface interface { // в котором будут методы, связанные с order } и так далее для каждой сущности.

2025-01-09 17:38 UTC, bulbetski commented on internal/repository/postgresql/balances_repository.go
> +		DO UPDATE SET accrual = gophermart_balances.accrual + excluded.accrual, updated_at = excluded.updated_at`,
updated_at берется из excluded.updated_at, но оно не передается в INSERT. Это приведет к ошибке при выполнении запроса.

Нужно заменить updated_at = NOW() в ON CONFLICT для обновления времени изменения записи.

2025-01-09 17:38 UTC, bulbetski commented on internal/repository/postgresql/balances_repository.go
> +		return service.ErrExecStmt
Лучше Оборачивать оригинальные ошибки в более информативные через fmt.Errorf и логировать на самом верхнем уровне. Тогда и отладить будет легко, 1 лог всего и в этом логе все стек ошибок

2025-01-09 17:38 UTC, bulbetski commented on internal/repository/postgresql/balances_repository.go
> +			return model.Balance{}, nil
ну тут как будто тоже стоило бы вернуть ErrNotFound и снаружи как-нибудь обработать

2025-01-09 17:38 UTC, bulbetski commented on internal/repository/postgresql/gophermart.go
> +	historyRepository service.HistoryRepository
вот методы всей этой шляпы надо сделать методами твоего repo

2025-01-09 17:38 UTC, bulbetski commented on internal/service/repository.go
> +type GophermartRepository interface {
все интерфейсы бы перенести по месту использования

2025-01-09 23:53 UTC, bulbetski requested changes
В целом норм, но сильно избегаешь указателей. Мощный интрумент, который позволяет экономить память и используется повсеместно

2025-01-09 23:53 UTC, bulbetski commented on internal/repository/postgresql/gophermart.go
> +		panic(err)
Про паники надо забыть. Весь сетап выполнять в мейне и не лениться хэндлить ошибки

2025-01-09 23:53 UTC, bulbetski commented on internal/repository/postgresql/order_repository.go
> +		`INSERT INTO gophermart_orders (order_id, owner_user_id, status) VALUES ($1, $2, 'NEW')`,
Статус тоже всегда стоит передавать как аргумент. Хардкодить не есть хорошо. То же самое сделать с PROCESSING

2025-01-09 23:53 UTC, bulbetski commented on internal/repository/postgresql/order_repository.go
> +		case ordersCh <- order:
Может случится такое, что мы будем писать в закрытый канал -- это вызовет панику. Отправить должен закрывать канал. Или это как-то должно правильно контролироваться. Типа вернуть массив, снаружи где-то в горутине переписать в канал итд

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/history_service.go
> +	var models []model.WithdrawHistoryResponse
models не оч информативное название. Это либо массив "историй", либо массив респонсов

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/history_service.go
> +	resp, err := h.repo.GetUsersHistory(ctx, userID)
это не resp, это history или UserHistory. resp у наc в http и grpc

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/order_service.go
> +			return o.repo.PostNewOrder(ctx, orderID, userID)
ну вообще сделать бы обратную логику. Если судить по названию метода, то он должен создать новый заказ. 
Тогда мы просто вызываем репозиторный метод для создаения, пытаемся заинсертить order_id, который должен быть уникальным. Если конфликт, то возвращаем конфликтующий заказ через ON CONFLICT DO NOTHING и RETURNING.

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/order_service.go
> +	}
любые конвертации из dbo в dto (или их массивов) и наоборот стоит выносить в хелперы

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/service.go
> +	historyServ transport.HistoryService
странно иметь такую же схему как с репозиторием, сделай тоже 1 структуру да и всё. Потом разбивать можно интерфейсами по месту использования

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/service.go
> +	historyServ transport.HistoryService
Или оставить как есть, но сделать так, чтобы каждый из сервисов принимал только интерфейс нужного репозитория вместо одного большого repo service.GophermartRepository. 

Так же иниализацию репозитория и сервисов надо вынести в мэйн. Инициализация какой-то непонятной темы в контрукторах это так себе практика, надо без сайд эффектов просто всё передать в аргументах функции

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/user_service.go
> +		UserID:       uuid.NewString()[:UserIDLength],
Генерация UserID через uuid.NewString()[:UserIDLength] может привести к коллизиям. Что в таком случае делаем?

2025-01-09 23:53 UTC, bulbetski commented on internal/service/gophermart/user_service.go
> +		UserID:       uuid.NewString()[:UserIDLength],
От коллизий можно избавиться сделав просто uuid.NewString()

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +	balanceRepo service.BalancesRepository
вот вместо этого можно использовать свой кастомный интерфейс

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +		ticker:      time.NewTicker(time.Second * 1),
Было бы здорово брать из конфига

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +				close(orders)
Канал надо закрывать только из отправителя. Иначе может возникнуть паника

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +	cancel context.CancelFunc,
тут cancelfunc избыточен. Достаточно проверять 
case <-ctx.Done(): // Используем Done вместо вызова cancel().
Да и quit канал как будто тоже не нужен, если используем контекст

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +			w.log.Error(fmt.Sprintf("%s: failed to register new order", fn), "error", err.Error())
идем дальше после ошибки, наверное тут должен быть continue

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +			time.AfterFunc(manyReqErr.RetryAfter+time.Second, func() {
`AfterFunc` с асинхронной логикой может усложнить отладку.
Если контекст завершён, `AfterFunc` всё равно запустит отложенный вызов

2025-01-09 23:53 UTC, bulbetski commented on internal/service/worker/accrual.go
> +func (w *worker) updateOrderInfo(ctx context.Context, status model.OrderStatus, userID string) {
как будто нужно добавить проверку `ctx.Err()` перед вызовом методов репозитория

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/accrual/client.go
> +			Timeout: 10 * time.Second,
Жестко задан таймаут, его бы конфигурировать

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/accrual/client.go
> +	req.Header.Set("Content-Type", "plain/text")
использование заголовка `Content-Type` для GET-запроса избыточно

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/accrual/client.go
> +	b, err := io.ReadAll(resp.Body)
Перед этим надо проверить, что body не nil

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/http/handler.go
> +	historyService transport.HistoryService
вот тут уже норм иметь разделение. Только интерфейсы написать бы прям над структурой handler.

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/http/post_order.go
> +	body, err := io.ReadAll(r.Body)
Проверить наличие body

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/http/post_withdraw.go
> +	body, err := io.ReadAll(r.Body)
проверить наличие body

2025-01-09 23:53 UTC, bulbetski commented on internal/transport/http/register_user.go
> +	body, err := io.ReadAll(r.Body)
проверить наличие body

2025-01-09 23:53 UTC, bulbetski commented on internal/types/float_decimal.go
> +	floatVal, _ := dec.Float64()
часто игнорируешь ошибки, не надо их игнорировать

2025-01-09 23:53 UTC, bulbetski commented on internal/types/float_decimal.go
> +		*f = FloatDecimal(decimal.NewFromFloat(floatVal))
в го можно вызывать методы над nil структурами, поэтому в этом месте потенциально можен быть паника. Вначале метода надо проверить, что f != nil

2025-01-10 08:00 UTC, Makovey commented on internal/app/app.go
> +
По задумке, даже если не стартанула внешняя система, приложение должно все равно принимать заявки.
Но return'ы все же стоит добавить)
Сделал

2025-01-10 08:46 UTC, Makovey commented on internal/app/app.go
> +	deps *deps
Идея была, все зависимости хранить только в `deps`.
Встроил `deps` в `App`, теперь обращение к зависимостям внутри `App` - напрямую

2025-01-10 09:27 UTC, Makovey commented on internal/db/migrations/20241130124046_new_gophermart_users_table.sql
> +    created_at TIMESTAMP DEFAULT (current_timestamp AT TIME ZONE 'Europe/Moscow')
Добавил NOT NULL + явно вставляю дату в репозиториях

2025-01-10 09:48 UTC, Makovey commented on internal/repository/postgresql/balances_repository.go
> +		DO UPDATE SET accrual = gophermart_balances.accrual + excluded.accrual, updated_at = excluded.updated_at`,
Хм, вроде не стреляло, но заменил на всякий случай

2025-01-10 11:07 UTC, Makovey commented on internal/service/gophermart/order_service.go
> +	}
Вынес

2025-01-10 11:09 UTC, Makovey commented on internal/service/gophermart/history_service.go
> +	var models []model.WithdrawHistoryResponse
Изменено

2025-01-10 11:09 UTC, Makovey commented on internal/service/gophermart/history_service.go
> +	resp, err := h.repo.GetUsersHistory(ctx, userID)
Изменено

2025-01-10 11:11 UTC, Makovey commented on internal/service/gophermart/user_service.go
> +		UserID:       uuid.NewString()[:UserIDLength],
При коллизии юзер получит ошибку, что надо попробовать еще раз.
Ограничил ради удобства, убрал

2025-01-10 11:56 UTC, Makovey commented on internal/transport/accrual/client.go
> +	b, err := io.ReadAll(resp.Body)
В документации сказано, что тело не может быть nil.
`The http Client and Transport guarantee that Body is always non-nil, even on responses without a body or responses with a zero-length body. It is the caller's responsibility to close Body.`

2025-01-10 13:54 UTC, Makovey commented on internal/service/worker/accrual.go
> +	cancel context.CancelFunc,
И правда, переделал

2025-01-10 14:07 UTC, Makovey commented on internal/service/worker/accrual.go
> +				close(orders)
Согласен, исправил

2025-01-10 14:13 UTC, Makovey commented on internal/repository/postgresql/order_repository.go
> +		case ordersCh <- order:
Переделал, теперь отправитель закрывает канал

2025-01-10 14:43 UTC, Makovey commented on internal/service/worker/accrual.go
> +			time.AfterFunc(manyReqErr.RetryAfter+time.Second, func() {
Принял, исправил

2025-01-10 14:52 UTC, Makovey commented on internal/service/worker/accrual.go
> +			w.log.Error(fmt.Sprintf("%s: failed to register new order", fn), "error", err.Error())
Да, ты прав, исправил

2025-01-10 14:59 UTC, Makovey commented on internal/service/worker/accrual.go
> +func (w *worker) updateOrderInfo(ctx context.Context, status model.OrderStatus, userID string) {
Добавил

2025-01-10 15:16 UTC, Makovey commented on internal/types/float_decimal.go
> +	floatVal, _ := dec.Float64()
Именно в этом случае возвращается не ошибка, а булька.
`Float64 returns the nearest float64 value for d and a bool indicating whether f represents d exactly.`

2025-01-12 08:33 UTC, Makovey commented on internal/app/deps.go
> +}
Убрал всю панику из кода.
Теперь инициализация дергается из main, и там же реакция на ошибки

2025-01-13 15:28 UTC, Makovey commented on internal/config/config.go
> +	}
Убрал дублирующиеся участки кода

2025-01-13 15:56 UTC, Makovey commented on internal/transport/accrual/client.go
> +			Timeout: 10 * time.Second,
Добавил конфигурацию

2025-01-13 15:56 UTC, Makovey commented on internal/service/worker/accrual.go
> +		ticker:      time.NewTicker(time.Second * 1),
Сделал

2025-01-13 17:35 UTC, Makovey commented on internal/repository/postgresql/gophermart.go
> +	historyRepository service.HistoryRepository
Сделал

2025-01-13 18:40 UTC, Makovey commented on internal/repository/postgresql/balances_repository.go
> +}
Сделано

2025-01-13 18:40 UTC, Makovey commented on internal/service/repository.go
> +type GophermartRepository interface {
Сделано

2025-01-13 18:40 UTC, Makovey commented on internal/repository/postgresql/gophermart.go
> +		panic(err)
Сделано

2025-01-13 18:41 UTC, Makovey commented on internal/service/gophermart/service.go
> +	historyServ transport.HistoryService
Оставил как есть, но теперь каждый сервис получает на вход только нужный ему репозиторий, логику инциализации вынес в мейн

2025-01-13 18:41 UTC, Makovey commented on internal/service/worker/accrual.go
> +	balanceRepo service.BalancesRepository
Сделано

2025-01-13 18:53 UTC, Makovey commented on internal/transport/http/handler.go
> +	historyService transport.HistoryService
Перенес

2025-01-13 18:54 UTC, Makovey commented on internal/types/float_decimal.go
> +		*f = FloatDecimal(decimal.NewFromFloat(floatVal))
Добавил guard проверку

2025-01-13 19:27 UTC, Makovey commented on internal/repository/postgresql/balances_repository.go
> +		return service.ErrExecStmt
Сделал

2025-01-13 19:33 UTC, Makovey commented on internal/repository/postgresql/balances_repository.go
> +			return model.Balance{}, nil
Вернул ошибку и явно создаю пустую структуру в сервисе

2025-01-13 19:40 UTC, Makovey commented on internal/repository/postgresql/order_repository.go
> +		`INSERT INTO gophermart_orders (order_id, owner_user_id, status) VALUES ($1, $2, 'NEW')`,
Убрал

2025-01-13 19:52 UTC, Makovey commented on internal/service/gophermart/order_service.go
> +			return o.repo.PostNewOrder(ctx, orderID, userID)
Может не совсем тебя понял. Но тут вот что происходит:
Сперва пытаемся получить заказ, если его нет в базе, значит его можно создать
Если он принадлежит другому юзеру, то одна ошибка, если заказ уже есть, то другая.
Мне показалось, что тут слишком много логики для одного sql запроса
Пока оставил как есть

2025-01-15 07:33 UTC, bulbetski approved these changes
Всё круто сделал, в основном по неймингу остались замечания, исправишь по желанию.

2025-01-15 07:33 UTC, bulbetski commented on internal/db/migrations/20241130124046_new_gophermart_users_table.sql
> +    created_at TIMESTAMP NOT NULL
timestamp надо использовать с таймзоной для корректной работы (если кайф, в личке поясню, лень писать), так же, чтобы не инсертить каждый раз created_at, можно сделать default CURRENT_TIMESTAMP или NOW().

2025-01-15 07:33 UTC, bulbetski commented on internal/repository/postgresql/history_repository.go
> +package postgresql
из названий файлов можно убрать _repository. Файлы и так находятся в пакете repository

2025-01-15 07:33 UTC, bulbetski commented on internal/service/adapter/balance.go
> +package adapter
паттерн адаптер обычно используется, когда нам надо интерфейс одной структуры смапить на интерфейс другой структуры, обычно когда дело касается каких-то запросов. Тут конечно тонко и не то, чтобы неправильно. Но функции в твоем пакете выполняют элементарную конвертацию типов и до адаптеров не дотягивают. Я бы это просто вынес из пакета в какой-нибудь файл под названием helpers

2025-01-15 07:33 UTC, bulbetski commented on internal/service/gophermart/balance_service.go
> +type BalancesServiceRepository interface {
Можно убрать service из названия. Просто BalanceRepository

2025-01-15 07:33 UTC, bulbetski commented on internal/service/gophermart/service.go
> +	historyServ http.HistoryService
буквы сэкономил и теперь кажется, что не сервис, а сервер, т.к. обычно сервер сокращают до serv. Стоит написать полностью -- *Service. То же самое касается структуры

2025-01-15 07:33 UTC, bulbetski commented on internal/service/worker/accrual.go
> +type WorkerRepository interface {
тут как будто OrdersRepository, потому что если бы было WorkerRepository, то репозиторий должен был бы доставать из репозитория то, что связано с воркерами. То есть называем интерфейсы по сути по названию сущности, с которой работают методы

2025-01-15 07:33 UTC, bulbetski commented on internal/transport/accrual/client.go
> +type HTTPClient struct {
круто было бы вынести в отдельную либу, но это так, домашка

2025-01-15 07:33 UTC, bulbetski commented on internal/transport/http/handler.go
> +}
приватные поля не оч круто, давай назовем их. 
И вопрос, вот эта структура очень похожа на структуру serv, в которой тоже сервисы. Поч они дублируются?

2025-01-15 07:33 UTC, bulbetski commented on internal/types/float_decimal.go
> +	floatVal, _ := dec.Float64()
ну в случае чего-то ж она возникает. Сам не знаю, в случае чего, но игнорировать не стоит

2025-01-15 13:09 UTC, Makovey commented on internal/transport/http/handler.go
> +}
А это просто интерфейс объединяющий другие интерфейсы, для удобства передачи их в хендлеры и создания моков. А встроил я их, чтобы он автоматом имплементил остальные интерфейсы, в остальном он никак не учавствует.
В общем потер его, так себе затея, теперь каждый сервис живет отдельно

2025-01-15 13:10 UTC, Makovey commented on internal/transport/accrual/client.go
> +type HTTPClient struct {
Хорошая идея, подумаю как обернуть

2025-01-15 13:10 UTC, Makovey commented on internal/service/worker/accrual.go
> +type WorkerRepository interface {
Согласен, ошибочно

2025-01-15 13:10 UTC, Makovey commented on internal/db/migrations/20241130124046_new_gophermart_users_table.sql
> +    created_at TIMESTAMP NOT NULL
Принял, поменял

2025-01-15 13:10 UTC, Makovey commented on internal/repository/postgresql/history_repository.go
> +package postgresql
Убрал

2025-01-15 13:11 UTC, Makovey commented on internal/service/adapter/balance.go
> +package adapter
Перетащил

2025-01-15 13:11 UTC, Makovey commented on internal/service/gophermart/balance_service.go
> +type BalancesServiceRepository interface {
Сделано

2025-01-15 13:11 UTC, Makovey commented on internal/service/gophermart/service.go
> +	historyServ http.HistoryService
Переименовал

2025-01-15 13:14 UTC, Makovey commented on internal/types/float_decimal.go
> +	floatVal, _ := dec.Float64()
Нашел в доке похожий метод, который мне больше подходит.
Заменил

2025-01-15 13:50 UTC, merged